### ISSUE TITLE
Add Open Shading Language support

### ISSUE THREAD

**Issue by jimmac** [flathub/org.blender.Blender#3]
There are some fun shaders written in python using the OSL[1]. Would be nice to be able to use them.

[1] https://blenderartists.org/forum/showthread.php?329295-Bevel-shader&p=2592665&viewfull=1#post2592665
[2] https://docs.blender.org/manual/en/dev/render/cycles/nodes/osl.html

**Comment by bochecha** [comment]
I just pushed a new Blender build using (almost) the same build options as the upstream binaries, with many added optional dependencies.

Can you test whether this is fixed? (I have a feeling it won't be, but I'd like to be sure)

**Comment by bochecha** [comment]
Looking some more into this, I'm fairly confident this hasn't been fixed by my recent changes to the build.

I had added `-DWITH_CYCLES_OSL:BOOL=ON` to enable building the OSL stuff, but the Blender buildsystem finds that the OSL libraries are missing, so it… just sets the option to OFF instead of failing the build as I expected. 😑 

Building OSL is a challenge, because the Flatpak SDK ships at the moment with [LLVM 4.0.1](https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/org.freedesktop.Sdk.json.in#L1190), but OSL 1.7.5 (the one official Blender binaries use) can [only be built with LLVM <= 3.5](https://github.com/imageworks/OpenShadingLanguage/issues/480#issuecomment-153439525).

I'm not sure I want to build an ancient LLVM in the Blender Flatpak just so I can build OSL…

**Comment by bochecha** [comment]
@jimmac do you still want this in 2.80?

**Comment by jimmac** [comment]
the bevel edges shader has been actually implemented in the core so i think i can live without this.

**Comment by ricvelozo** [comment]
[OSL now supports LLVM 9](https://github.com/imageworks/OpenShadingLanguage/pull/1058). Can it be enabled?

**Comment by bochecha** [comment]
That pull request was merged a month ago… Is that in an OSL release yet? Does Blender work with it?

If you reply "yes" to both, then yes, we can enable it.

**Comment by ricvelozo** [comment]
At least, [OSL works with LLVM 3.9 (PR closed 2 years ago)](https://github.com/imageworks/OpenShadingLanguage/pull/693), with the fix to the issue in https://github.com/flathub/org.blender.Blender/issues/3#issuecomment-366451031. I think it works with LLVM 8, too. But, I don't know if Blender works with it; in the makefiles it seems to look for any 1.* version.

**Comment by plafue** [comment]
Hi there :wave: This issue has been open for a while....

I tested using the [sample OSL shader mentioned in the documentation](https://docs.blender.org/manual/en/2.93/render/shader_nodes/osl.html#writing-shaders) with the latest published flatpak and it seems to work as expected:

![image](https://user-images.githubusercontent.com/1915763/121531878-1c165080-c9ff-11eb-8363-bb21efea74b0.png)

It'd be great if you could close this issue, as it seems to be outdated.
