### ISSUE TITLE
Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.blender.Blender#4]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by bochecha** [comment]
Agreed.

I took the appdata from the Fedora package though, because upstream does not have one.

There's a comment in the appdata file saying:

```
BugReportURL: Long discussions with sergey on #blendercoders
BugReportURL: http://lists.blender.org/pipermail/bf-committers/2014-September/044217.html
SentUpstream: 2014-09-23
```

Someone would need to restart that conversation with upstream, because the file really needs to live there, so that they can provide up to date screenshot, and translate it.

**Comment by Pointedstick** [comment]
I submitted an AppStream file upstream, FWIW: https://developer.blender.org/T53611

**Comment by bochecha** [comment]
@Pointedstick thanks for championing this, I haven't had time to do it myself and it definitely is needed.

**Comment by Pointedstick** [comment]
My patch was accepted upstream, so we should be able to just use that now. They didn't opt to include the `<release>` tag that I provided, so we should probably add this ourselves (even if it's just a stab, with no actual release notes) so that downstream consumers of this information are able to provide users with Blender's current version number.

**Comment by bochecha** [comment]
> They didn't opt to include the <release> tag that I provided

That's too bad. 🙁 

I see they also used the `<launchable type="desktop">blender.desktop</launchable>` line. I have no idea whether that works, and whether `flatpak-builder` will do the right thing here when renaming the `blender.desktop` file to `org.blender.Blender.desktop`.

This rename really ought to go upstream as well by the way… Do you still have some energy left to try and start that conversation? 🙂

**Comment by Pointedstick** [comment]
Submitted another patch to add `<release>` information: https://developer.blender.org/D3065

If they accept this, maybe my gravitas will have grown enough to try renaming their desktop file to match the AppStream ID.

**Comment by bochecha** [comment]
We've had screenshots in the appdata for a while now, this probably can be closed.
